 matrix:
   include:
     - os: linux
       dist: xenial
       sudo: required
     - os: osx
       osx_image: xcode8.2
  allow_failures:
   - os: linux

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - ./.travis/before_install.sh

script: ./build-cmake.sh