language: cpp

sudo: required

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
    - os: osx
      osx_image: xcode8.2
      compiler: clang
    - os: osx
      osx_image: xcode8.2
      compiler: gcc
  allow_failures:
    - os: osx

before_install:
  # - ./.travis/before_install.sh
  - apt-get update && apt-get upgrade
  - apt-get install -y cmake

script: ./build-cmake.sh