language: cpp

sudo: required

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode8.2
  allow_failures:
    - os: linux

compiler:
  - clang
  - gcc

before_install:
  - ./.travis/before_install.sh

script: ./build-cmake.sh