language: cpp

sudo: required

matrix:
  include:
  - os: linux
    dist: yakkety
    compiler: clang
  - os: linux
    dist: yakkety
    compiler: gcc
  - os: osx
    osx_image: xcode8.2
    compiler: clang
  - os: osx
    osx_image: xcode8.2
    compiler: gcc
  allow_failures:
  - os: osx

before_install:
  # - ./.travis/before_install.sh
  # - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  # - sudo apt-get install -y gcc-6 g++-6
  - sudo apt-get install -y libboost-all-dev openssl libssl-dev
  - sudo apt-get install -y cmake libcppnetlib-dev
  # - dpkg-query -L libcppnetlib-dev

script: CMAKE_C_COMPILER=$CC CMAKE_CXX_COMPILER=$CXX ./build-cmake.sh