language: cpp

sudo: required

# https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/?
matrix:
  include:
  - os: linux

    dist: xenial
    compiler: clang
    env: CMAKE_C_COMPILER=clang-3.8 CMAKE_CXX_COMPILER=clang++-3.8
  - os: linux
    dist: xenial
    compiler: gcc
    env: CMAKE_C_COMPILER=gcc-6 CMAKE_CXX_COMPILER=g++-6
  - os: osx
    osx_image: xcode8.2
    compiler: clang
    env: CMAKE_C_COMPILER=clang CMAKE_CXX_COMPILER=clang++
  - os: osx
    osx_image: xcode8.2
    compiler: gcc
    env: CMAKE_C_COMPILER=gcc CMAKE_CXX_COMPILER=g++
  allow_failures:
  - os: linux

before_install:
  - ./.travis/before_install.sh

script: CMAKE_C_COMPILER=$CMAKE_C_COMPILER CMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER ./build-cmake.sh