language: cpp

sudo: required

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
    - os: osx
      osx_image: xcode8.2
      compiler: clang
    - os: osx
      osx_image: xcode8.2
      compiler: gcc
  allow_failures:
    - os: osx

before_install:
  # - ./.travis/before_install.sh
  - sudo apt-get update # && sudo apt-get upgrade
  - sudo apt-get install -y cmake libboost-all-dev openssl libssl-dev libcppnetlib-dev
  - dpkg-query -L libcppnetlib-dev

script: ./build-cmake.sh