#! /usr/bin/env python
# encoding: utf-8


def build(bld):
    lib_excl = [
        'main.cpp',
        ]
    if not bld.options.debug:
        lib_excl.append('debug.hpp')

    lib_name = 'cppiemlib'
    iemlib_src = bld.path.ant_glob('**/*.cpp', excl=lib_excl)
    bld.shlib(source=iemlib_src, target='cppiemlib', name=lib_name)
    bld.program(source='main.cpp', target='cppiemlib.o', use=[lib_name])

    # if bld.options.iem_build_tests:
    #     gtest_excl = []
    #     bld.shlib(
    #         source=bld.path.ant_glob('**/*_test.cpp', excl=gtest_excl),
    #         target='cppiemtest',
    #         name='cppiemtestlib',
    #         use=[lib_name],
    #        lib=['gtest']
    #     )
