#! /usr/bin/env python
# encoding: utf-8

def build(bld):
    lib_excl = [
        'main.cpp',
        '**/*_test.cpp',
        'strategy/fedpolicy.cpp',
        'strategy/house.cpp',
        'strategy/senate.cpp',
        ]
    if not bld.options.debug:
        lib_excl.append('debug.hpp')

    lib_name = 'iemlib'
    iemlib_src = bld.path.ant_glob('**/*.cpp', excl=lib_excl)
    bld.shlib(source=iemlib_src, target='iem', name=lib_name)
    bld.program(source='main.cpp', target='iem.o', use=[lib_name])

    if bld.options.test:
        gtest_excl = []
        bld.shlib(
            source=bld.path.ant_glob('**/*_test.cpp', excl=gtest_excl),
            target='iemtest',
            name='iemtestlib',
            use=[lib_name],
            lib=['gtest']
        )
